services:
  postgres:
    image: 'postgres:latest'
    command: -c config_file=/etc/postgresql.conf
    environment:
      - 'POSTGRES_DB=jobs'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5435:5432'
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
